
CREATE TABLE 
(
  KEYWORD_ID VARCHAR(50) NOT NULL COMMENT '피로개선_ID',
  SUPP_ID    VARCHAR(50) NOT NULL COMMENT '영양제리스트'
);

CREATE TABLE EFFECT
(
  EFFECT     NOT NULL,
  EFFECT_ID  NOT NULL,
  PRIMARY KEY (EFFECT_ID)
) COMMENT '필요효과기대';

CREATE TABLE HISTORYDISEASE
(
  HISTORYDISEASE    VARCHAR(50) NOT NULL COMMENT '질병이력',
  HISTORYDISEASE_ID VARCHAR(50) NOT NULL COMMENT '질병이력_ID',
  PRIMARY KEY (HISTORYDISEASE_ID)
) COMMENT '질병이력';

CREATE TABLE Inquiry
(
  INQUIRY_ID    VARCHAR(500) NOT NULL COMMENT '댓글_ID',
  DATE          TIMESTAMP    NOT NULL COMMENT '작성일자',
  CONTENT       VARCHAR(500) NOT NULL COMMENT '내용',
  RESPONSE      VARCHAR(500) NOT NULL COMMENT '응답',
  RESPONSE_DATE VARCHAR(500) NOT NULL COMMENT '응답_일자',
  ADMINE_ID     VARCHAR(500) NOT NULL COMMENT '관리자_ID',
  MEMBER_ID     VARCHAR(50)  NOT NULL COMMENT '회원번호ID',
  PRIMARY KEY (INQUIRY_ID)
) COMMENT '문의';

CREATE TABLE MEMBERSINFOR
(
  MEMBER_ID         VARCHAR(50)  NOT NULL COMMENT '회원번호ID',
  NAME              VARCHAR(50)  NOT NULL COMMENT '이름',
  ID                VARCHAR(50)  NOT NULL COMMENT '아이디',
  PASSWORD          VARCHAR(50)  NOT NULL COMMENT '비밀번호',
  BIRTHDATE         VARCHAR(50)  NOT NULL COMMENT '생년월일',
  AGE               VARCHAR(50)  NOT NULL COMMENT '나이',
  SEX_ID            VARCHAR(50)  NOT NULL COMMENT '성별_ID',
  ADDRESS           VARCHAR(50)  NOT NULL COMMENT '주소',
  PHONE             VARCHAR(50)  NOT NULL COMMENT '연락처',
  HISTORYDISEASE_ID VARCHAR(50)  NOT NULL COMMENT '질병이력_ID',
  ALLERGIES_ID      VARCHAR(50)  NOT NULL COMMENT '알레르기_ID',
  REGISTRATIONDATE  VARCHAR(50)  NOT NULL COMMENT '가입일',
  EMAIL             VARCHAR(50)  NOT NULL COMMENT '이메일',
  PAYMENT_ID        VARCHAR(50)  NOT NULL COMMENT '결제정보_ID',
  ADMINE_ID         VARCHAR(500) NOT NULL COMMENT '관리자_ID',
  PRIMARY KEY (MEMBER_ID)
) COMMENT '회원정보';

CREATE TABLE PAYMENT
(
  PAYMENT    VARCHAR(50) NOT NULL COMMENT '결제정보',
  PAYMENT_ID VARCHAR(50) NOT NULL COMMENT '결제정보_ID',
  SUPP_ID    VARCHAR(50) NOT NULL COMMENT '영양제리스트',
  PRIMARY KEY (PAYMENT_ID)
) COMMENT ' 결제정보';

CREATE TABLE RECOVERY_LIST
(
  KEYWORD_ID  VARCHAR(50) NOT NULL COMMENT '피로개선_ID',
  PRODUCT     VARCHAR(50) NULL     COMMENT '이름',
  MANUFACTURE VARCHAR(50) NULL     COMMENT '제조사',
  COMPONENT1  VARCHAR(50) NULL     COMMENT '성분1',
  COMPONENT2  VARCHAR(50) NULL     COMMENT '성분2',
  TYPE        VARCHAR(50) NULL     COMMENT '영양제 제형',
  DOSAGE      VARCHAR(50) NULL     COMMENT '용량',
  EFFECT_ID               NOT NULL COMMENT '필요효과기대_ID',
  FREQUENCY   VARCHAR(50) NULL     COMMENT '복용 주기',
  SIDEEFFECTS VARCHAR(50) NULL     COMMENT '부작용',
  SUPP_ID     VARCHAR(50) NOT NULL COMMENT '영양제리스트',
  PRIMARY KEY (KEYWORD_ID)
) COMMENT '영양제 상세정보';

CREATE TABLE Review
(
  REVIEW_ID  VARCHAR(500) NOT NULL COMMENT '리뷰_ID',
  DATE       VARCHAR(500) NULL     COMMENT '작성일자',
  CONTENT    VARCHAR(500) NULL     COMMENT '내용',
  VIEW_COUNT VARCHAR(500) NULL     COMMENT '조회수',
  MEMBER_ID  VARCHAR(50)  NOT NULL COMMENT '회원번호ID',
  SUPP_ID    VARCHAR(50)  NOT NULL COMMENT '영양제리스트',
  PRIMARY KEY (REVIEW_ID)
) COMMENT '리뷰';

CREATE TABLE SEX
(
  SEX    VARCHAR(50) NOT NULL COMMENT '성별',
  SEX_ID VARCHAR(50) NOT NULL COMMENT '성별_ID',
  PRIMARY KEY (SEX_ID)
) COMMENT '성별';

CREATE TABLE SUPP_LIST
(
  SUPP_ID    VARCHAR(50)  NULL     COMMENT '영양제리스트',
  KEYWORD_ID VARCHAR(50)  NOT NULL COMMENT '기능별_ID',
  KEYWORD    VARCHAR(50)  NOT NULL COMMENT '기능별 ',
  Admin_ID   VARCHAR(500) NOT NULL COMMENT '관리자_ID',
  PRIMARY KEY (SUPP_ID)
) COMMENT '영양제 리스트';

ALTER TABLE MEMBERSINFOR
  ADD CONSTRAINT FK_SEX_TO_MEMBERSINFOR
    FOREIGN KEY (SEX_ID)
    REFERENCES SEX (SEX_ID);

ALTER TABLE MEMBERSINFOR
  ADD CONSTRAINT FK_HISTORYDISEASE_TO_MEMBERSINFOR
    FOREIGN KEY (HISTORYDISEASE_ID)
    REFERENCES HISTORYDISEASE (HISTORYDISEASE_ID);

ALTER TABLE MEMBERSINFOR
  ADD CONSTRAINT FK_PAYMENT_TO_MEMBERSINFOR
    FOREIGN KEY (PAYMENT_ID)
    REFERENCES PAYMENT (PAYMENT_ID);

ALTER TABLE Inquiry
  ADD CONSTRAINT FK_MEMBERSINFOR_TO_Inquiry
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBERSINFOR (MEMBER_ID);

ALTER TABLE Review
  ADD CONSTRAINT FK_MEMBERSINFOR_TO_Review
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBERSINFOR (MEMBER_ID);

ALTER TABLE Review
  ADD CONSTRAINT FK_SUPP_LIST_TO_Review
    FOREIGN KEY (SUPP_ID)
    REFERENCES SUPP_LIST (SUPP_ID);

ALTER TABLE 
  ADD CONSTRAINT FK_RECOVERY_LIST_TO_
    FOREIGN KEY (KEYWORD_ID)
    REFERENCES RECOVERY_LIST (KEYWORD_ID);

ALTER TABLE 
  ADD CONSTRAINT FK_SUPP_LIST_TO_
    FOREIGN KEY (SUPP_ID)
    REFERENCES SUPP_LIST (SUPP_ID);

ALTER TABLE RECOVERY_LIST
  ADD CONSTRAINT FK_EFFECT_TO_RECOVERY_LIST
    FOREIGN KEY (EFFECT_ID)
    REFERENCES EFFECT (EFFECT_ID);

ALTER TABLE PAYMENT
  ADD CONSTRAINT FK_SUPP_LIST_TO_PAYMENT
    FOREIGN KEY (SUPP_ID)
    REFERENCES SUPP_LIST (SUPP_ID);
