
CREATE TABLE Admin
(
  Admin_ID VARCHAR(500) NOT NULL COMMENT '관리자_ID',
  Name     VARCHAR(500) NOT NULL COMMENT '이름',
  E-mail   VARCHAR(500) NOT NULL COMMENT '이메일',
  PRIMARY KEY (Admin_ID)
) COMMENT '관리자';

CREATE TABLE ALLERGIES
(
  ALLERGIES    VARCHAR(50) NOT NULL COMMENT '알레르기',
  ALLERGIES_ID VARCHAR(50) NOT NULL COMMENT '알레르기_ID',
  PRIMARY KEY (ALLERGIES_ID)
) COMMENT '알레르기이력';

CREATE TABLE HISTORYDISEASE
(
  HISTORYDISEASE    VARCHAR(50) NOT NULL COMMENT '질병이력',
  HISTORYDISEASE_ID VARCHAR(50) NOT NULL COMMENT '질병이력_ID',
  PRIMARY KEY (HISTORYDISEASE_ID)
) COMMENT '질병이력';

CREATE TABLE Inquiry
(
  Inquiry_ID    VARCHAR(500) NOT NULL COMMENT '댓글_ID',
  DATE          VARCHAR(500) NOT NULL COMMENT '작성일자',
  Content       VARCHAR(500) NOT NULL COMMENT '내용',
  User_ID       VARCHAR(500) NOT NULL COMMENT '작성자_ID',
  Response      VARCHAR(500) NOT NULL COMMENT '응답',
  Response_Date VARCHAR(500) NOT NULL COMMENT '응답_일자',
  Admin_ID      VARCHAR(500) NOT NULL COMMENT '관리자_ID',
  PRIMARY KEY (Inquiry_ID)
) COMMENT '문의';

CREATE TABLE MEMBERSINFOR
(
  MEMBER_ID         VARCHAR(50) NOT NULL COMMENT '회원번호ID',
  NAME              VARCHAR(50) NOT NULL COMMENT '이름',
  ID                VARCHAR(50) NOT NULL COMMENT '아이디',
  PASSWORD          VARCHAR(50) NOT NULL COMMENT '비밀번호',
  BIRTHDATE         VARCHAR(50) NOT NULL COMMENT '생년월일',
  AGE               VARCHAR(50) NOT NULL COMMENT '나이',
  SEX_ID            VARCHAR(50) NOT NULL COMMENT '성별_ID',
  ADDRESS           VARCHAR(50) NOT NULL COMMENT '주소',
  PHONE             VARCHAR(50) NOT NULL COMMENT '연락처',
  HISTORYDISEASE_ID VARCHAR(50) NOT NULL COMMENT '질병이력_ID',
  ALLERGIES_ID      VARCHAR(50) NOT NULL COMMENT '알레르기_ID',
  REGISTRATIONDATE  VARCHAR(50) NOT NULL COMMENT '가입일',
  EMAIL             VARCHAR(50) NOT NULL COMMENT '이메일',
  PAYMENT_ID        VARCHAR(50) NOT NULL COMMENT '결제정보_ID',
  PRIMARY KEY (MEMBER_ID)
) COMMENT '회원정보';

CREATE TABLE PAYMENT
(
  PAYMENT    VARCHAR(50) NOT NULL COMMENT '결제정보',
  PAYMENT_ID VARCHAR(50) NOT NULL COMMENT '결제정보_ID',
  PRIMARY KEY (PAYMENT_ID)
) COMMENT ' 결제정보';

CREATE TABLE SEX
(
  SEX    VARCHAR(50) NOT NULL COMMENT '성별',
  SEX_ID VARCHAR(50) NOT NULL COMMENT '성별_ID',
  PRIMARY KEY (SEX_ID)
) COMMENT '성별';

CREATE TABLE User
(
  User_ID VARCHAR(500) NOT NULL COMMENT '작성자_ID',
  Name    VARCHAR(500) NOT NULL COMMENT '이름',
  E-mail  VARCHAR(500) NOT NULL COMMENT '이메일',
  PRIMARY KEY (User_ID)
) COMMENT '작성자';

ALTER TABLE MEMBERSINFOR
  ADD CONSTRAINT FK_SEX_TO_MEMBERSINFOR
    FOREIGN KEY (SEX_ID)
    REFERENCES SEX (SEX_ID);

ALTER TABLE MEMBERSINFOR
  ADD CONSTRAINT FK_HISTORYDISEASE_TO_MEMBERSINFOR
    FOREIGN KEY (HISTORYDISEASE_ID)
    REFERENCES HISTORYDISEASE (HISTORYDISEASE_ID);

ALTER TABLE MEMBERSINFOR
  ADD CONSTRAINT FK_ALLERGIES_TO_MEMBERSINFOR
    FOREIGN KEY (ALLERGIES_ID)
    REFERENCES ALLERGIES (ALLERGIES_ID);

ALTER TABLE MEMBERSINFOR
  ADD CONSTRAINT FK_PAYMENT_TO_MEMBERSINFOR
    FOREIGN KEY (PAYMENT_ID)
    REFERENCES PAYMENT (PAYMENT_ID);

ALTER TABLE Inquiry
  ADD CONSTRAINT FK_User_TO_Inquiry
    FOREIGN KEY (User_ID)
    REFERENCES User (User_ID);

ALTER TABLE Inquiry
  ADD CONSTRAINT FK_Admin_TO_Inquiry
    FOREIGN KEY (Admin_ID)
    REFERENCES Admin (Admin_ID);

    
CREATE TABLE CHOLESTEROL_LIST
(
  KEYWORD_ID  VARCHAR(50)  NOT NULL COMMENT '콜레스테롤 _ID',
  KEYWORD     VARCHAR(50)  NOT NULL COMMENT '콜레스테롤',
  PRODUCT     VARCHAR(50)  NOT NULL COMMENT '이름',
  MANUFACTURE VARCHAR(50)  NOT NULL COMMENT '제조사',
  EFFECT      VARCHAR(500) NOT NULL COMMENT '필요기대효과',
  COMPONENT1  VARCHAR(50)  NOT NULL COMMENT '성분1',
  COMPONENT2  VARCHAR(50)  NOT NULL COMMENT '성분2',
  TYPE        VARCHAR(50)  NOT NULL COMMENT '영양제 제형',
  DOSAGE      VARCHAR(50)  NOT NULL COMMENT '용량',
  FREQUENCY   VARCHAR(50)  NOT NULL COMMENT '복용 주기',
  SIDEEFFECTS VARCHAR(50)  NOT NULL COMMENT '부작용',
  SUPP_ID     VARCHAR(50)  NOT NULL COMMENT '영양제리스트',
  PRIMARY KEY (KEYWORD_ID)
) COMMENT '콜레스테롤 개선';

CREATE TABLE EYES_LIST
(
  KEYWORD_ID  VARCHAR(50)  NOT NULL COMMENT '눈_ID',
  KEYWORD     VARCHAR(50)  NOT NULL COMMENT '눈',
  PRODUCT     VARCHAR(50)  NOT NULL COMMENT '이름',
  MANUFACTURE VARCHAR(50)  NOT NULL COMMENT '제조사',
  EFFECT      VARCHAR(500) NOT NULL COMMENT '필요기대효과',
  COMPONENT1  VARCHAR(50)  NOT NULL COMMENT '성분1',
  COMPONENT2  VARCHAR(50)  NOT NULL COMMENT '성분2',
  TYPE        VARCHAR(50)  NOT NULL COMMENT '영양제 제형',
  DOSAGE      VARCHAR(50)  NOT NULL COMMENT '용량',
  FREQUENCY   VARCHAR(50)  NOT NULL COMMENT '복용 주기',
  SIDEEFFECTS VARCHAR(50)  NOT NULL COMMENT '부작용',
  SUPP_ID     VARCHAR(50)  NOT NULL COMMENT '영양제리스트',
  PRIMARY KEY (KEYWORD_ID)
) COMMENT '눈 기능 개선';

CREATE TABLE LIVER_LIST
(
  KEYWORD_ID  VARCHAR(50)  NOT NULL COMMENT '간_ID',
  KEYWORD     VARCHAR(50)  NOT NULL COMMENT '간',
  PRODUCT     VARCHAR(50)  NOT NULL COMMENT '이름',
  MANUFACTURE VARCHAR(50)  NOT NULL COMMENT '제조사',
  EFFECT      VARCHAR(500) NOT NULL COMMENT '필요기대효과',
  COMPONENT1  VARCHAR(50)  NOT NULL COMMENT '성분1',
  COMPONENT2  VARCHAR(50)  NOT NULL COMMENT '성분2',
  TYPE        VARCHAR(50)  NOT NULL COMMENT '영양제 제형',
  DOSAGE      VARCHAR(50)  NOT NULL COMMENT '용량',
  FREQUENCY   VARCHAR(50)  NOT NULL COMMENT '복용 주기',
  SIDEEFFECTS VARCHAR(50)  NOT NULL COMMENT '부작용',
  SUPP_ID     VARCHAR(50)  NOT NULL COMMENT '영양제리스트',
  PRIMARY KEY (KEYWORD_ID)
) COMMENT '간 기능개선';

CREATE TABLE RECOVERY_LIST
(
  KEYWORD_ID  VARCHAR(50)  NOT NULL COMMENT '피로개선_ID',
  KEYWORD     VARCHAR(50)  NULL     COMMENT '피로개선',
  PRODUCT     VARCHAR(50)  NULL     COMMENT '이름',
  MANUFACTURE VARCHAR(50)  NULL     COMMENT '제조사',
  EFFECT      VARCHAR(500) NULL     COMMENT '필요기대효과',
  COMPONENT1  VARCHAR(50)  NULL     COMMENT '성분1',
  COMPONENT2  VARCHAR(50)  NULL     COMMENT '성분2',
  TYPE        VARCHAR(50)  NULL     COMMENT '영양제 제형',
  DOSAGE      VARCHAR(50)  NULL     COMMENT '용량',
  FREQUENCY   VARCHAR(50)  NULL     COMMENT '복용 주기',
  SIDEEFFECTS VARCHAR(50)  NULL     COMMENT '부작용',
  SUPP_ID     VARCHAR(50)  NOT NULL COMMENT '영양제리스트',
  PRIMARY KEY (KEYWORD_ID)
) COMMENT '피로회복';

CREATE TABLE SUPP_LIST
(
  SUPP_ID    VARCHAR(50) NOT NULL COMMENT '영양제리스트',
  KEYWORD_ID VARCHAR(50) NOT NULL COMMENT '기능별_ID',
  KEYWORD    VARCHAR(50) NOT NULL COMMENT '기능별 ',
  PRIMARY KEY (SUPP_ID)
) COMMENT '영양제 리스트';

ALTER TABLE CHOLESTEROL_LIST
  ADD CONSTRAINT FK_SUPP_LIST_TO_CHOLESTEROL_LIST
    FOREIGN KEY (SUPP_ID)
    REFERENCES SUPP_LIST (SUPP_ID);

ALTER TABLE RECOVERY_LIST
  ADD CONSTRAINT FK_SUPP_LIST_TO_RECOVERY_LIST
    FOREIGN KEY (SUPP_ID)
    REFERENCES SUPP_LIST (SUPP_ID);

ALTER TABLE EYES_LIST
  ADD CONSTRAINT FK_SUPP_LIST_TO_EYES_LIST
    FOREIGN KEY (SUPP_ID)
    REFERENCES SUPP_LIST (SUPP_ID);

ALTER TABLE LIVER_LIST
  ADD CONSTRAINT FK_SUPP_LIST_TO_LIVER_LIST
    FOREIGN KEY (SUPP_ID)
    REFERENCES SUPP_LIST (SUPP_ID);


CREATE TABLE Comment
(
  Comment_ID VARCHAR(500) NOT NULL COMMENT '댓글_ID',
  Date       VARCHAR(500) NULL     COMMENT '작성일자',
  Content    VARCHAR(500) NULL     COMMENT '내용',
  Review_ID  VARCHAR(500) NOT NULL COMMENT '작성자_ID',
  User_ID    VARCHAR(500) NOT NULL COMMENT '사용자_ID',
  PRIMARY KEY (Comment_ID)
) COMMENT '댓글';

CREATE TABLE Review
(
  Review_ID  VARCHAR(500) NOT NULL COMMENT '리뷰_ID',
  Date       VARCHAR(500) NULL     COMMENT '작성일자',
  Content    VARCHAR(500) NULL     COMMENT '내용',
  View_Count VARCHAR(500) NULL     COMMENT '조회수',
  User_ID    VARCHAR(500) NOT NULL COMMENT '사용자_ID',
  PRIMARY KEY (Review_ID)
) COMMENT '리뷰';

CREATE TABLE User
(
  User_ID VARCHAR(500) NOT NULL COMMENT '사용자_ID',
  Name    VARCHAR(500) NULL     COMMENT '이름',
  E-mail  VARCHAR(500) NULL     COMMENT '이메일',
  PRIMARY KEY (User_ID)
) COMMENT '사용자';

ALTER TABLE Review
  ADD CONSTRAINT FK_User_TO_Review
    FOREIGN KEY (User_ID)
    REFERENCES User (User_ID);

ALTER TABLE Comment
  ADD CONSTRAINT FK_Review_TO_Comment
    FOREIGN KEY (Review_ID)
    REFERENCES Review (Review_ID);

ALTER TABLE Comment
  ADD CONSTRAINT FK_User_TO_Comment
    FOREIGN KEY (User_ID)
    REFERENCES User (User_ID);

